publisher_position_controllers:
  ros__parameters:

    wait_sec_between_publish: 5
    publish_topic: "/position_controllers/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, 0.785]
    pos2: [0, 0]
    pos3: [-0.785, -0.785]
    pos4: [0, 0]
